#!/usr/bin/env bash

TARGETS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=./_builder.sh
source "${TARGETS_DIR}/_builder.sh"

TARGET_DOMAIN="${TARGET_DOMAIN:-jb.mythic3011.com}"
TARGET_HOST="${TARGET_HOST:-66.154.127.33}"
TARGET_SSH_PORT="${TARGET_SSH_PORT:-10000}"
TARGET_SSH_USER="${TARGET_SSH_USER:-root}"
TARGET_REMOTE_ROOT="${TARGET_REMOTE_ROOT:-/opt/jobs-boards-jb}"
TARGET_APP_PORT="${TARGET_APP_PORT:-127.0.0.1:18080}"
TARGET_APP_SSL_PORT="${TARGET_APP_SSL_PORT:-127.0.0.1:18443}"
TARGET_COMPOSE_PROJECT_NAME="${TARGET_COMPOSE_PROJECT_NAME:-jobs-boards-jb}"
TARGET_BT_STATE_DIR="${TARGET_BT_STATE_DIR:-/opt/jobs-boards-jb/state}"
TARGET_SKIP_HOST_PORT_EXPOSURE_CHECK="${TARGET_SKIP_HOST_PORT_EXPOSURE_CHECK:-true}"
TARGET_DB_DATABASE="${TARGET_DB_DATABASE:-jobs_boards}"
TARGET_DB_USERNAME="${TARGET_DB_USERNAME:-jobs_boards}"
TARGET_MONITORING_ADMIN_USERNAME="${TARGET_MONITORING_ADMIN_USERNAME:-admin}"
TARGET_TIMEZONE="${TARGET_TIMEZONE:-Asia/Hong_Kong}"

build_reverse_proxy_target
