#!/usr/bin/env bash

TARGETS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=./_builder.sh
source "${TARGETS_DIR}/_builder.sh"

: "${LAB_DEPLOY_HOST:?Set LAB_DEPLOY_HOST for the target lab VM}"

TARGET_PROFILE_NAME="${TARGET_PROFILE_NAME:-lab-env}"

# shellcheck disable=SC2034
# These DEPLOY_* variables are the sourced output contract consumed by ops/deploy/vps-deploy.sh.
DEPLOY_PROFILE_NAME="${TARGET_PROFILE_NAME:-lab-env}"
DEPLOY_PROFILE_KIND="${TARGET_PROFILE_KIND:-lab}"
DEPLOY_DOMAIN="${LAB_DEPLOY_DOMAIN:-jobs-board.lab}"
DEPLOY_HOST="${LAB_DEPLOY_HOST}"
DEPLOY_SSH_PORT="${LAB_DEPLOY_SSH_PORT:-22}"
DEPLOY_SSH_USER="${LAB_DEPLOY_SSH_USER:-root}"
DEPLOY_REMOTE_ROOT="${LAB_DEPLOY_REMOTE_ROOT:-/opt/jobs-boards-lab}"
DEPLOY_APP_PORT="${LAB_DEPLOY_APP_PORT:-80}"
DEPLOY_APP_SSL_PORT="${LAB_DEPLOY_APP_SSL_PORT:-443}"
DEPLOY_APP_URL="${LAB_DEPLOY_APP_URL:-https://${DEPLOY_DOMAIN}}"
DEPLOY_ASSET_URL="${LAB_DEPLOY_ASSET_URL:-https://${DEPLOY_DOMAIN}}"
DEPLOY_COMPOSE_PROJECT_NAME="${LAB_DEPLOY_COMPOSE_PROJECT_NAME:-jobs-boards-lab}"
DEPLOY_BT_STATE_DIR="${LAB_DEPLOY_BT_STATE_DIR:-/opt/jobs-boards-lab/state}"
DEPLOY_DB_DATABASE="${LAB_DEPLOY_DB_DATABASE:-jobs_boards}"
DEPLOY_DB_USERNAME="${LAB_DEPLOY_DB_USERNAME:-jobs_boards}"
DEPLOY_MONITORING_ADMIN_USERNAME="${LAB_DEPLOY_MONITORING_ADMIN_USERNAME:-admin}"
DEPLOY_MONITORING_ACCESS_MODE="${LAB_DEPLOY_MONITORING_ACCESS_MODE:-$(resolve_target_monitoring_access_mode)}"
DEPLOY_MONITORING_ALLOWED_CIDRS="${LAB_DEPLOY_MONITORING_ALLOWED_CIDRS:-$(resolve_target_monitoring_allowed_cidrs)}"
DEPLOY_TIMEZONE="${LAB_DEPLOY_TIMEZONE:-Asia/Hong_Kong}"
DEPLOY_INSTALL_HOST_NGINX="false"
DEPLOY_NGINX_SITE_NAME=""
DEPLOY_NGINX_CERT_PATH=""
DEPLOY_NGINX_KEY_PATH=""
DEPLOY_NGINX_PROXY_PASS=""

LAB_CONFIGURE_NETPLAN="${LAB_CONFIGURE_NETPLAN:-false}"
LAB_NETPLAN_APPLY="${LAB_NETPLAN_APPLY:-false}"
LAB_WAN_IFACE="${LAB_WAN_IFACE:-eth0}"
LAB_WAN_MODE="${LAB_WAN_MODE:-dhcp}"
LAB_WAN_ADDRESS="${LAB_WAN_ADDRESS:-}"
LAB_WAN_GATEWAY="${LAB_WAN_GATEWAY:-}"
LAB_WAN_DNS="${LAB_WAN_DNS:-1.1.1.1,8.8.8.8}"
LAB_LAN_IFACE="${LAB_LAN_IFACE:-eth1}"
LAB_LAN_ADDRESS="${LAB_LAN_ADDRESS:-192.168.153.2/24}"
