type: leaky
name: local/path-scanner
description: "Detect 404 scanner for sensitive files (php, asp, env, git, bak)"
filter: >
  evt.Meta.log_type == 'http_access-log' &&
  evt.Meta.http_status == '404' &&
  evt.Parsed.uri matches '.*\\.(php|asp|env|git|bak).*'
groupby: evt.Meta.source_ip
capacity: 15
leakspeed: "5s"
blackhole: 1h
labels:
  behavior: "http:scan"
  remediation: true
