location = /.env {
    set $blue_team_trap_name env_probe;
    access_log /var/log/nginx/fp-trap.log blue_team_honeypot;
    return 403;
}

location = /.git/config {
    set $blue_team_trap_name git_probe;
    access_log /var/log/nginx/fp-trap.log blue_team_honeypot;
    return 403;
}

location = /phpmyadmin {
    set $blue_team_trap_name phpmyadmin_probe;
    access_log /var/log/nginx/fp-trap.log blue_team_honeypot;
    return 403;
}

location = /wp-login.php {
    set $blue_team_trap_name wp_probe;
    access_log /var/log/nginx/fp-trap.log blue_team_honeypot;
    return 403;
}

location = /admin-old {
    set $blue_team_trap_name admin_old_probe;
    access_log /var/log/nginx/fp-trap.log blue_team_honeypot;
    return 403;
}
