[supervisord]
nodaemon=true
user=root
logfile=/dev/stdout
logfile_maxbytes=0
logfile_backups=0

[program:php]
command=%(ENV_PHP_BIN)s -d variables_order=EGPCS /var/www/html/artisan serve --host=0.0.0.0 --port=80 --no-reload
environment=PHP_BIN=%(ENV_PHP_BIN)s,DB_SSLMODE=%(ENV_DB_SSLMODE)s
user=sail
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stdout_logfile_backups=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stderr_logfile_backups=0
redirect_stderr=false
