[supervisord]
nodaemon=true
user=root
logfile=/dev/stdout
logfile_maxbytes=0
logfile_backups=0

[program:php]
command=/usr/sbin/php-fpm8.5 -F
environment=DB_SSLMODE="%(ENV_DB_SSLMODE)s",CANONICAL_AUDIT_AUTH_SERVICE_KEY_ID="%(ENV_CANONICAL_AUDIT_AUTH_SERVICE_KEY_ID)s",CANONICAL_AUDIT_AUTH_SERVICE_SECRET="%(ENV_CANONICAL_AUDIT_AUTH_SERVICE_SECRET)s",CANONICAL_AUDIT_AUTH_SERVICE_ALLOWED_CIDRS="%(ENV_CANONICAL_AUDIT_AUTH_SERVICE_ALLOWED_CIDRS)s"
user=root
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stdout_logfile_backups=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stderr_logfile_backups=0
redirect_stderr=false
