<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\QueryException;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;
use Laravel\Fortify\TwoFactorAuthenticatable;
use Spatie\Permission\Traits\HasRoles;

/**
 * @property string $idcode
 * @property string $login_id
 * @property string $nickname
 * @property string $email
 * @property string $password
 * @property string $user_type
 * @property string|null $profile_image_path
 * @property \Illuminate\Support\Carbon|null $locked_until
 * @property string|null $two_factor_secret
 * @property array<int,string>|null $two_factor_recovery_codes
 * @property \Illuminate\Support\Carbon|null $two_factor_confirmed_at
 *
 * @method static self create(array $attributes = [])
 */
class User extends Authenticatable
{
    use HasFactory, Notifiable, HasRoles, TwoFactorAuthenticatable, HasUuids;

    public const AUTH_IDENTIFIER = 'login_id';

    /**
     * The primary key associated with the table.
     */
    protected $primaryKey = 'id';

    /**
     * The data type of the auto-incrementing ID.
     */
    protected $keyType = 'string';

    /**
     * Indicates if the IDs are auto-incrementing.
     */
    public $incrementing = false;

    protected static function boot(): void
    {
        parent::boot();

        static::creating(static function (self $user) {
            // Generate idcode for business logic (separate from database id)
            if (empty($user->idcode)) {
                $user->idcode = 'user_' . Str::uuid()->toString();
            }
            // Note: The 'id' field is auto-generated by PostgreSQL using gen_random_uuid()
        });
        
            static::created(static function () {
                Cache::forget('dashboard.stats');
            });
        
            static::updated(static function () {
                Cache::forget('dashboard.stats');
            });
        
            static::deleted(static function () {
                Cache::forget('dashboard.stats');
            });
    }

    /**
     * The attributes that are mass assignable.
     *
     * @var list<string>
     */
    protected $fillable = [
        'idcode',
        'login_id',
        'nickname',
        'email',
        'password',
        'user_type',
        'profile_image_path',
        'locked_until',
        'two_factor_secret',
        'two_factor_recovery_codes',
        'two_factor_confirmed_at',
        'password_changed_at',
    ];

    /**
     * Expose a name attribute that proxies to nickname for UI compatibility.
     */
    public function getNameAttribute(): string
    {
        return $this->nickname ?? '';
    }

    /**
     * Allow setting name to populate nickname field.
     */
    public function setNameAttribute(string $value): void
    {
        $this->attributes['nickname'] = $value;
    }

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var list<string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'locked_until' => 'datetime',
            'password' => 'hashed',
            'two_factor_confirmed_at' => 'datetime',
            'password_changed_at' => 'datetime',
        ];
    }

    /**
     * Get the name of the unique identifier for the user.
     */
    public function getAuthIdentifierName(): string
    {
        return self::AUTH_IDENTIFIER;
    }

    /**
     * Get the unique identifier for the user (UUID id for database storage).
     * This is used when storing the user in sessions, while getAuthIdentifierName()
     * is used for authentication lookup by login_id.
     */
    public function getAuthIdentifier(): mixed
    {
        return $this->getKey();
    }

    /**
     * Check if user is locked.
     */
    public function isLocked(): bool
    {
        return $this->locked_until && $this->locked_until->isFuture();
    }

    /**
     * Check if user is a system admin.
     */
    public function isAdmin(): bool
    {
        if ($this->user_type === 'admin') {
            return true;
        }

        if (! $this->canResolveAdminRole()) {
            return false;
        }

        try {
            return $this->hasRole('admin');
        } catch (QueryException) {
            return false;
        }
    }

    private function canResolveAdminRole(): bool
    {
        $permissionTables = config('permission.table_names', []);
        $rolesTable = $permissionTables['roles'] ?? 'roles';
        $modelHasRolesTable = $permissionTables['model_has_roles'] ?? 'model_has_roles';

        return Schema::hasTable($rolesTable) && Schema::hasTable($modelHasRolesTable);
    }

    /**
     * Check if user is a company.
     */
    public function isCompany(): bool
    {
        return $this->user_type === 'company';
    }

    /**
     * Check if user is an individual.
     */
    public function isIndividual(): bool
    {
        return $this->user_type === 'individual';
    }

    /**
     * Get formatted user type label.
     */
    public function getUserTypeLabel(): string
    {
        return match($this->user_type) {
            'admin' => 'Admin',
            'company' => 'Company',
            'individual' => 'Individual',
            default => ucfirst($this->user_type),
        };
    }

    /**
     * Get the job postings for this company user.
     */
    public function jobPostings(): HasMany
    {
        return $this->hasMany(JobPosting::class, 'company_user_id');
    }

    /**
     * Get the applications submitted by this individual user.
     */
    public function applications(): HasMany
    {
        return $this->hasMany(Application::class, 'applicant_user_id');
    }
}
