apiVersion: 1
datasources:
  - name: JobsBoards-Postgres
    type: postgres
    url: postgres:5432
    database: ${DB_DATABASE}
    user: ${DB_USERNAME}
    secureJsonData:
      password: ${DB_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1500
